[package]
name = "camera_thread"
version = "0.1.0"
authors = ["Denis Golubev <dgolubev.public@gmail.com>"]

[dependencies]
error-chain = "0.7.2"
rscam = "0.5.3"

[dev-dependencies]
gfx = "0.13.0"
gfx_device_gl = "0.12.0"
gfx_window_glutin = "0.13.1"
glutin = "0.7.2"
