//! This module contains the error types this library uses (which are generated by the
//! [error_chain](https://crates.io/crates/error_chain) crate).

error_chain! {
    errors {
        /// An error which occurs when the device does not exist at the given location.
        CameraNotAvailable(camera: String) {
            description("the given camera is not available")
            display("the camera '{}' is not available", camera)
        }

        /// An error which occurs, when there are issues with the configuration. E.g. the
        /// wrong resolution / frame rate is selected.
        ConfigurationError {
            description("an error occurred during configuration (see the cause for details)")
            display("an error occurred during configuration (see the cause for details)")
        }

        /// An error which occurs, when there capturing a frame fails.
        CaptureError {
            description("failed to capture a frame (see the cause for details)")
        }

        /// An error which occurs, when sending the frame fails.
        SendError {
            description("failed to send the captured frame (see the cause for details)")
        }

        /// An error which occurs, when receiving the frame fails.
        ReceiveError {
            description("failed to receive the captured frame (remote channel disconnected)")
        }
    }
}
